PODCAST_DATA_SOURCE_PLUGINS: ""
ARTICLES_DATA_SOURCE_PLUGINS: []
ARXIV_DATA_SOURCE_PLUGINS: []
HACKER_NEWS_DATA_SOURCE_PLUGINS: []
NEWSLETTER_RSS_DATA_SOURCE_PLUGINS: []
SQLITE_DATA_SOURCE_PLUGINS: []

PODCAST_INTRO_PLUGINS: standardIntroPlugin
PODCAST_SCRAPER_PLUGINS: defaultScraperPlugin
PODCAST_SEGMENT_WRITER_PLUGINS: topTenSegmentWriterPlugin
PODCAST_OUTRO_PLUGINS: outroWriterPlugin
PODCAST_PRODUCER_PLUGINS: producerPlugin
PODCAST_NAME: "Slop Pod"
PODCAST_TYPE: "Memes and internet culture"
PODCAST_DESCRIPTION: "This is a podcast about the internet, memes and the people and stories behind it all"
LLM_MODEL_PROVIDER: "anthropic"
LLM_MODEL_VERSION_NAME: "claude-3-5-sonnet-latest"
OPENAI_MAX_TOKENS_SUMMARY: 2048
OPENAI_TEMPERATURE_SUMMARY: 0.7
TTS_SCRIPT: "ttsLocalScript.sh"
SHOULD_PAUSE_AND_VALIDATE_STORIES_BEFORE_SCRAPING: "false"