{{- define "mypodcast.envVars" -}}
#! This is the configuration file for the podcast generator

PODCAST_DATA_SOURCE_PLUGINS={{ .Values.PODCAST_DATA_SOURCE_PLUGINS }}
PODCAST_INTRO_PLUGINS={{ .Values.PODCAST_INTRO_PLUGINS }}
PODCAST_SCRAPER_PLUGINS={{ .Values.PODCAST_SCRAPER_PLUGINS }}
PODCAST_SEGMENT_WRITER_PLUGINS={{ .Values.PODCAST_SEGMENT_WRITER_PLUGINS }}
PODCAST_OUTRO_PLUGINS={{ .Values.PODCAST_OUTRO_PLUGINS }}
PODCAST_PRODUCER_PLUGINS={{ .Values.PODCAST_PRODUCER_PLUGINS }}

{{- if (regexMatch ".*redditAPIPlugin.*" .Values.PODCAST_DATA_SOURCE_PLUGINS) }}
SUBREDDIT={{ .Values.SUBREDDIT }}
{{- end }}

{{- if (regexMatch ".*articlesRSSFeedPlugin.*" .Values.PODCAST_DATA_SOURCE_PLUGINS) }}
ARTICLES_RSS_FEEDS={{ .Values.ARTICLES_RSS_FEEDS }}
NUMBER_OF_ITEMS_TO_FETCH={{ .Values.NUMBER_OF_ITEMS_TO_FETCH }}
{{- end }}

{{- if (regexMatch ".*podcastFeedPlugin.*" .Values.PODCAST_DATA_SOURCE_PLUGINS) }}
PODCAST_FEEDS={{ .Values.PODCAST_FEEDS }}
NUMBER_OF_ITEMS_TO_FETCH={{ .Values.NUMBER_OF_ITEMS_TO_FETCH }}
{{- end }}

{{- if (regexMatch ".*sqliteTokenPlugin.*" .Values.PODCAST_DATA_SOURCE_PLUGINS) }}
TOKEN_STORIES_DB_PATH={{ .Values.TOKEN_STORIES_DB_PATH }}
{{- end }}

{{- if (regexMatch ".*newsletterRSSFeedPlugin.*" .Values.PODCAST_DATA_SOURCE_PLUGINS) }}
ARTICLES_RSS_FEEDS={{ .Values.ARTICLES_RSS_FEEDS }}
NUMBER_OF_ITEMS_TO_FETCH={{ .Values.NUMBER_OF_ITEMS_TO_FETCH }}
{{- end }}

{{- if (regexMatch ".*hackerNewsAPIPlugin.*" .Values.PODCAST_DATA_SOURCE_PLUGINS) }}
NUMBER_OF_POSTS_TO_FETCH={{ .Values.NUMBER_OF_POSTS_TO_FETCH }}
{{- end }}

{{- if (regexMatch ".*arxivApiPlugin.*" .Values.PODCAST_DATA_SOURCE_PLUGINS) }}
ARXIV_SEARCH_QUERY={{ .Values.ARXIV_SEARCH_QUERY }}
{{- end }}

SHOULD_PAUSE_AND_VALIDATE_STORIES_BEFORE_SCRAPING={{ .Values.SHOULD_PAUSE_AND_VALIDATE_STORIES_BEFORE_SCRAPING }}

PODCAST_NAME="{{ .Values.PODCAST_NAME }}"
PODCAST_TYPE="{{ .Values.PODCAST_TYPE }}"
PODCAST_DESCRIPTION="{{ .Values.PODCAST_DESCRIPTION }}"

LLM_MODEL_PROVIDER={{ .Values.LLM_MODEL_PROVIDER }}
OPENAI_MODEL_SUMMARY={{ .Values.OPENAI_MODEL_SUMMARY }}
OPENAI_MAX_TOKENS_SUMMARY={{ .Values.OPENAI_MAX_TOKENS_SUMMARY }}
OPENAI_TEMPERATURE_SUMMARY={{ .Values.OPENAI_TEMPERATURE_SUMMARY }}

TTS_SCRIPT={{ .Values.TTS_SCRIPT }}
{{- end }}
