---
# Source: mypodcast/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mypodcast-config
data:
  config.env: |
    
    #! This is the configuration file for the podcast generator
    
    PODCAST_DATA_SOURCE_PLUGINS=sqliteTokenPlugin
    PODCAST_INTRO_PLUGINS=standardIntroPlugin
    PODCAST_SCRAPER_PLUGINS=tokenResearchScraperPlugin
    PODCAST_SEGMENT_WRITER_PLUGINS=topTenSegmentWriterPlugin
    PODCAST_OUTRO_PLUGINS=outroWriterPlugin
    PODCAST_PRODUCER_PLUGINS=producerPlugin
    TOKEN_STORIES_DB_PATH=/Users/davidnorman/clanker-launch-bot/tokens.db
    
    SHOULD_PAUSE_AND_VALIDATE_STORIES_BEFORE_SCRAPING=true
    
    PODCAST_NAME="Slop Cast"
    PODCAST_TYPE="Meme Coins"
    PODCAST_DESCRIPTION="An autonomously generated podcast about meme coins written by FOMO Bot"
    
    LLM_MODEL_PROVIDER=openai
    OPENAI_MODEL_SUMMARY=gpt-4o-mini
    OPENAI_MAX_TOKENS_SUMMARY=4096
    OPENAI_TEMPERATURE_SUMMARY=0.2
    
    TTS_SCRIPT=ttsLocalScript.sh

