name: Python unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9.17
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f podcastTextGenerationApp/ci-requirements.txt ]; then pip install -r podcastTextGenerationApp/ci-requirements.txt; fi
    
    - name: Set PYTHONPATH and run tests
      run: |
        export PYTHONPATH=${PYTHONPATH}:$(pwd)/podcastTextGenerationApp
        echo "PYTHONPATH=$PYTHONPATH:$(pwd)/podcastTextGenerationApp" >> $GITHUB_ENV
    
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=7.5 $(git ls-files '*.py')

    - name: Run Tests
      run : |
        python -m unittest

