name: Python unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.17

    - name: Set PYTHONPATH and run tests
      run: |
        echo $(pwd)
        echo "PYTHONPATH=\$PYTHONPATH:$(pwd)/podcastTextGenerationApp" >> $GITHUB_ENV
        python -m unittest
